### ISSUE TITLE
Does not work on OSX 10.9

### ISSUE THREAD

**Issue by JARMourato** [sbhklr/QRCoder#2]

**Comment by sebromero** [comment]
Hey @JARMourato, thank you for reporting this. What exactly isn't working? Can you elaborate?

**Comment by JARMourato** [comment]
Hey @sbhklr ! QRCoder does not work if you the 10.9 version of OSX is the deployment version target. That is visible in your code since you use : @available(OSX 10.10, *). In your requirements you say that the minimum required version is 10.9. Nevertheless, either you make it support 10.9 with some minor changes in your code, or change the requirements. If you want, i can submit a pull request for the necessary changes to support OSX 10.9

Thanks alot ;)

**Comment by sebromero** [comment]
Fixed in latest version.
