### ISSUE TITLE
Swift 4 support?

### ISSUE THREAD

**Issue by firanto** [sbhklr/QRCoder#6]
Is this library still maintained? Swift is now around version 4.1 and this libs can't even run at Swift 3?

**Comment by Narragansett** [comment]
I second that. Too many issues, hoping such good work could be maintained by the developer.

**Comment by sebromero** [comment]
Hi @kurotsukikaitou and @Narragansett ! I've been away for a year. I'm currently looking into this. Thank you for you patience.

**Comment by sebromero** [comment]
Now implemented in version 1.0

**Comment by firanto** [comment]
Thanks... That was fast... 👍
