### ISSUE TITLE
Text Encoding problem

### ISSUE THREAD

**Issue by Jobsecond** [sbhklr/QRCoder#8]
Hi @sbhklr,
It seems that non-ASCII characters (e.g. `你好`, `おはよう`) cannot be encoded correctly. When I scan the generated QR code, those non-ASCII characters are replaced with question mark `?`.

**Comment by sebromero** [comment]
Hi @Jobsecond,
Thank you for pointing this out. I'm working on a fix.

**Comment by sebromero** [comment]
@Jobsecond Please check out the `encoding-fix` branch and let me know if that fixes your issue. You'll have to invoke it as follows:
```
let image = qrCodeGenerator.createImage(value: "你好", size: CGSize(width: 100, height: 100), encoding: .utf8)
```

**Comment by Jobsecond** [comment]
@sbhklr
Thanks for the fix. It works.

**Comment by sebromero** [comment]
@Jobsecond Great, I'll release a new version.
